name: cesi_covid_19_tracker
description: A PoC for a covid-19 tracker

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^3.1.0
  json_serializable: ^3.2.5
  http: ^0.12.0+4
  provider_architecture:
  provider: ^3.1.0
  responsive_builder: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/virus.jpg
